### ISSUE TITLE
MANY2ONE doesn't work

### ISSUE THREAD

**Issue by drnextgis** [sacrud/sacrud_deform#15]
After this commit MANY2MANY issue was fixed https://github.com/sacrud/sacrud_deform/commit/1889a0875770b7d998d00e419ee92686df06d3cd but MANY2ONE was broken.

**Comment by uralbash** [comment]
Please, check my last update https://github.com/sacrud/sacrud_deform/commit/7acdc1bd503b013f210f79c22d64095a589e749e

**Comment by drnextgis** [comment]
It works, thanks!
